/*
Tạo dimension, fact, ETL audit và staging objects

Quy ước:
- Surrogate/unknown key = -1
- fact_transaction grain = 1 dòng raw.transactions
- fact_pattern_transaction grain = 1 transaction trong 1 laundering attempt
- Fact lớn không khai báo FK vật lý để tối ưu bulk load; integrity được kiểm soát
  bằng ETL lookup + etl.validate_dw()
*/

DO $$
BEGIN
    IF current_database() <> 'aml_source' THEN
        RAISE EXCEPTION 'Sai database: hãy đổi connection sang aml_source trước khi chạy';
    END IF;
END
$$;

BEGIN;

CREATE TABLE IF NOT EXISTS etl.dw_batch
(
    dw_batch_id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    process_name                 TEXT NOT NULL DEFAULT 'IBM_AML_SOURCE_TO_DW',
    load_type                    VARCHAR(20) NOT NULL,
    status                       VARCHAR(20) NOT NULL,
    started_at                   TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    completed_at                 TIMESTAMPTZ,
    source_low_watermark         BIGINT NOT NULL DEFAULT 0,
    source_high_watermark        BIGINT NOT NULL DEFAULT 0,
    pattern_low_watermark        BIGINT NOT NULL DEFAULT 0,
    pattern_high_watermark       BIGINT NOT NULL DEFAULT 0,
    bank_rows_affected           BIGINT NOT NULL DEFAULT 0,
    entity_rows_affected         BIGINT NOT NULL DEFAULT 0,
    account_rows_affected        BIGINT NOT NULL DEFAULT 0,
    currency_rows_affected       BIGINT NOT NULL DEFAULT 0,
    payment_format_rows_affected BIGINT NOT NULL DEFAULT 0,
    transaction_rows_inserted    BIGINT NOT NULL DEFAULT 0,
    pattern_rows_inserted        BIGINT NOT NULL DEFAULT 0,
    rejected_rows                BIGINT NOT NULL DEFAULT 0,
    validation_status            VARCHAR(20),
    error_message                TEXT,
    CONSTRAINT ck_dw_batch_load_type CHECK (load_type IN ('FULL', 'INCREMENTAL')),
    CONSTRAINT ck_dw_batch_status CHECK (status IN ('STARTED', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_dw_batch_validation CHECK
        (validation_status IS NULL OR validation_status IN ('PASSED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS etl.dw_rejected_row
(
    dw_rejected_row_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dw_batch_id        BIGINT NOT NULL REFERENCES etl.dw_batch(dw_batch_id),
    source_object      TEXT NOT NULL,
    source_key         BIGINT,
    error_code         TEXT NOT NULL,
    error_description  TEXT NOT NULL,
    raw_payload        JSONB,
    rejected_at        TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS etl.dw_validation_result
(
    validation_result_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dw_batch_id          BIGINT NOT NULL REFERENCES etl.dw_batch(dw_batch_id),
    check_name           TEXT NOT NULL,
    source_value         NUMERIC(38,8),
    target_value         NUMERIC(38,8),
    status               VARCHAR(10) NOT NULL,
    details              TEXT,
    checked_at           TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT ck_dw_validation_status CHECK (status IN ('PASSED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS dw.dim_date
(
    date_key         INTEGER PRIMARY KEY,
    full_date        DATE NOT NULL UNIQUE,
    day_of_month     SMALLINT NOT NULL,
    day_of_week      SMALLINT NOT NULL,
    day_name         VARCHAR(10) NOT NULL,
    week_of_year     SMALLINT NOT NULL,
    month_number     SMALLINT NOT NULL,
    month_name       VARCHAR(10) NOT NULL,
    quarter_number   SMALLINT NOT NULL,
    year_number      SMALLINT NOT NULL,
    is_weekend       BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_time
(
    time_key        INTEGER PRIMARY KEY,
    time_value      TIME WITHOUT TIME ZONE NOT NULL UNIQUE,
    hour_number     SMALLINT NOT NULL,
    minute_number   SMALLINT NOT NULL,
    day_part        VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_currency
(
    currency_key  SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_name TEXT NOT NULL UNIQUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS dw.dim_payment_format
(
    payment_format_key SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_format     TEXT NOT NULL UNIQUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS dw.dim_bank
(
    bank_key    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id     TEXT NOT NULL UNIQUE,
    bank_name   TEXT NOT NULL,
    source_hash CHAR(32) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS dw.dim_entity
(
    entity_key  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id   TEXT NOT NULL UNIQUE,
    entity_name TEXT,
    source_hash CHAR(32) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS dw.dim_account
(
    account_key    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_key       BIGINT NOT NULL REFERENCES dw.dim_bank(bank_key),
    entity_key     BIGINT NOT NULL REFERENCES dw.dim_entity(entity_key),
    bank_id        TEXT NOT NULL,
    account_number TEXT NOT NULL,
    entity_id      TEXT,
    source_hash    CHAR(32) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to   TIMESTAMPTZ NOT NULL DEFAULT '9999-12-31 23:59:59+00',
    is_current     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT ux_dim_account_version UNIQUE (bank_id, account_number, effective_from),
    CONSTRAINT ck_dim_account_effective_range CHECK (effective_to > effective_from)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_account_current
    ON dw.dim_account (bank_id, account_number)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS ix_dim_account_bank_key ON dw.dim_account (bank_key);
CREATE INDEX IF NOT EXISTS ix_dim_account_entity_key ON dw.dim_account (entity_key);

CREATE TABLE IF NOT EXISTS dw.dim_pattern_type
(
    pattern_type_key SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_type     TEXT NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS dw.fact_transaction
(
    transaction_key       BIGINT PRIMARY KEY,
    source_transaction_id BIGINT NOT NULL,
    date_key              INTEGER NOT NULL,
    time_key              INTEGER NOT NULL,
    from_bank_key         BIGINT NOT NULL,
    to_bank_key           BIGINT NOT NULL,
    from_account_key      BIGINT NOT NULL,
    to_account_key        BIGINT NOT NULL,
    from_entity_key       BIGINT NOT NULL,
    to_entity_key         BIGINT NOT NULL,
    payment_currency_key  SMALLINT NOT NULL,
    receiving_currency_key SMALLINT NOT NULL,
    payment_format_key    SMALLINT NOT NULL,
    amount_paid           NUMERIC(24,8) NOT NULL,
    amount_received       NUMERIC(24,8) NOT NULL,
    is_laundering         BOOLEAN NOT NULL,
    is_cross_bank         BOOLEAN NOT NULL,
    is_cross_currency     BOOLEAN NOT NULL,
    is_self_transfer      BOOLEAN NOT NULL,
    implied_exchange_rate NUMERIC(38,12),
    source_load_batch_id  BIGINT NOT NULL,
    dw_batch_id           BIGINT NOT NULL,
    loaded_at             TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT ck_fact_transaction_amounts CHECK (amount_paid > 0 AND amount_received > 0)
);

CREATE TABLE IF NOT EXISTS dw.fact_pattern_transaction
(
    pattern_transaction_key BIGINT PRIMARY KEY,
    source_pattern_transaction_id BIGINT NOT NULL,
    pattern_attempt_id       BIGINT NOT NULL,
    pattern_type_key         SMALLINT NOT NULL REFERENCES dw.dim_pattern_type(pattern_type_key),
    pattern_sequence         INTEGER NOT NULL,
    pattern_description      TEXT NOT NULL,
    date_key                 INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    time_key                 INTEGER NOT NULL REFERENCES dw.dim_time(time_key),
    from_bank_key            BIGINT NOT NULL REFERENCES dw.dim_bank(bank_key),
    to_bank_key              BIGINT NOT NULL REFERENCES dw.dim_bank(bank_key),
    from_account_key         BIGINT NOT NULL REFERENCES dw.dim_account(account_key),
    to_account_key           BIGINT NOT NULL REFERENCES dw.dim_account(account_key),
    payment_currency_key     SMALLINT NOT NULL REFERENCES dw.dim_currency(currency_key),
    receiving_currency_key   SMALLINT NOT NULL REFERENCES dw.dim_currency(currency_key),
    payment_format_key       SMALLINT NOT NULL REFERENCES dw.dim_payment_format(payment_format_key),
    amount_paid              NUMERIC(24,8) NOT NULL,
    amount_received          NUMERIC(24,8) NOT NULL,
    is_laundering            BOOLEAN NOT NULL,
    source_load_batch_id     BIGINT NOT NULL,
    dw_batch_id              BIGINT NOT NULL,
    loaded_at                TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT ux_fact_pattern_attempt_sequence UNIQUE (pattern_attempt_id, pattern_sequence)
);

CREATE UNLOGGED TABLE IF NOT EXISTS stg.account_snapshot
(
    bank_id        TEXT NOT NULL,
    account_number TEXT NOT NULL,
    bank_key       BIGINT NOT NULL,
    entity_key     BIGINT NOT NULL,
    entity_id      TEXT,
    source_hash    CHAR(32) NOT NULL,
    PRIMARY KEY (bank_id, account_number)
);

CREATE OR REPLACE VIEW stg.v_transaction_enriched AS
SELECT
    t.*,
    to_char(t.transaction_timestamp, 'YYYYMMDD')::INTEGER AS date_key,
    to_char(t.transaction_timestamp, 'HH24MI')::INTEGER AS time_key,
    t.from_bank_id <> t.to_bank_id AS is_cross_bank,
    t.payment_currency <> t.receiving_currency AS is_cross_currency,
    t.from_bank_id = t.to_bank_id
        AND t.from_account_id = t.to_account_id AS is_self_transfer,
    CASE
        WHEN t.payment_currency <> t.receiving_currency AND t.amount_paid > 0
            THEN (t.amount_received / t.amount_paid)::NUMERIC(38,12)
        ELSE NULL
    END AS implied_exchange_rate
FROM raw.transactions t;

CREATE OR REPLACE VIEW stg.v_pattern_enriched AS
SELECT
    p.*,
    to_char(p.transaction_timestamp, 'YYYYMMDD')::INTEGER AS date_key,
    to_char(p.transaction_timestamp, 'HH24MI')::INTEGER AS time_key
FROM raw.laundering_pattern_transaction p;

-- Unknown members. BY DEFAULT identity cho phép chỉ định key -1.
INSERT INTO dw.dim_date
VALUES (-1, DATE '1900-01-01', 1, 1, 'Unknown', 1, 1, 'Unknown', 1, 1900, FALSE)
ON CONFLICT (date_key) DO NOTHING;

INSERT INTO dw.dim_time
VALUES (-1, TIME '00:00:59', 0, 0, 'Unknown')
ON CONFLICT (time_key) DO NOTHING;

INSERT INTO dw.dim_currency (currency_key, currency_name)
VALUES (-1, 'Unknown')
ON CONFLICT (currency_key) DO NOTHING;

INSERT INTO dw.dim_payment_format (payment_format_key, payment_format)
VALUES (-1, 'Unknown')
ON CONFLICT (payment_format_key) DO NOTHING;

INSERT INTO dw.dim_bank (bank_key, bank_id, bank_name, source_hash)
VALUES (-1, '~UNKNOWN', 'Unknown', md5('Unknown'))
ON CONFLICT (bank_key) DO NOTHING;

INSERT INTO dw.dim_entity (entity_key, entity_id, entity_name, source_hash)
VALUES (-1, '~UNKNOWN', 'Unknown', md5('Unknown'))
ON CONFLICT (entity_key) DO NOTHING;

INSERT INTO dw.dim_account
    (account_key, bank_key, entity_key, bank_id, account_number, entity_id,
     source_hash, effective_from, effective_to, is_current)
VALUES
    (-1, -1, -1, '~UNKNOWN', '~UNKNOWN', NULL,
     md5('Unknown'), '1900-01-01 00:00:00+00', '9999-12-31 23:59:59+00', TRUE)
ON CONFLICT (account_key) DO NOTHING;

INSERT INTO dw.dim_pattern_type (pattern_type_key, pattern_type)
VALUES (-1, 'Unknown')
ON CONFLICT (pattern_type_key) DO NOTHING;

-- Sinh đủ 1.440 phút trong ngày; time_key dùng dạng HHMM.
INSERT INTO dw.dim_time (time_key, time_value, hour_number, minute_number, day_part)
SELECT
    (extract(hour FROM tm)::INTEGER * 100 + extract(minute FROM tm)::INTEGER),
    tm::TIME,
    extract(hour FROM tm)::SMALLINT,
    extract(minute FROM tm)::SMALLINT,
    CASE
        WHEN extract(hour FROM tm) BETWEEN 5 AND 11 THEN 'Morning'
        WHEN extract(hour FROM tm) BETWEEN 12 AND 16 THEN 'Afternoon'
        WHEN extract(hour FROM tm) BETWEEN 17 AND 21 THEN 'Evening'
        ELSE 'Night'
    END
FROM generate_series(
    TIMESTAMP '2000-01-01 00:00:00',
    TIMESTAMP '2000-01-01 23:59:00',
    INTERVAL '1 minute'
) AS g(tm)
ON CONFLICT (time_key) DO NOTHING;

COMMIT;

COMMENT ON TABLE dw.fact_transaction IS
    'Grain: một dòng giao dịch từ raw.transactions; transaction_key bằng source_transaction_id để giữ lineage';
COMMENT ON TABLE dw.fact_pattern_transaction IS
    'Grain: một giao dịch theo sequence trong một laundering pattern attempt';
COMMENT ON COLUMN dw.fact_transaction.amount_paid IS
    'Phải phân tích cùng payment_currency_key; không cộng lẫn nhiều currency';
COMMENT ON COLUMN dw.fact_transaction.amount_received IS
    'Phải phân tích cùng receiving_currency_key; không cộng lẫn nhiều currency';
